# Generated by Django 4.2 on 2023-06-01 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercoupon',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
