# Generated by Django 4.2 on 2023-06-01 13:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0035_alter_order_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coupon', '0002_alter_usercoupon_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.CharField(max_length=50, unique=True)),
                ('discount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)])),
                ('min_value', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('valid_from', models.DateField(auto_now_add=True)),
                ('valid_till', models.DateField()),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='usercoupon',
            old_name='is_expired',
            new_name='used',
        ),
        migrations.RemoveField(
            model_name='usercoupon',
            name='coupon_code',
        ),
        migrations.RemoveField(
            model_name='usercoupon',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='usercoupon',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='usercoupon',
            name='minimum_amount',
        ),
        migrations.AddField(
            model_name='usercoupon',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='checkout.order'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usercoupon',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Productcoupon',
        ),
        migrations.AddField(
            model_name='usercoupon',
            name='coupon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='coupon.coupon'),
            preserve_default=False,
        ),
    ]
