# Generated by Django 4.2 on 2023-06-06 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0004_remove_usercoupon_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercoupon',
            name='total_price',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
