# Generated by Django 4.2 on 2023-05-20 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_color_remove_product_image_variations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
    ]
