# Generated by Django 4.2 on 2023-05-26 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_remove_variations_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='variations',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
