# Generated by Django 4.2 on 2023-05-27 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_variations_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
