# Generated by Django 4.2 on 2023-05-21 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_alter_cart_variation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='variation',
        ),
    ]
