# Generated by Django 4.2 on 2023-05-31 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_coupon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
