# Generated by Django 4.2 on 2023-06-08 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0044_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Processing', 'Processing'), ('Pending', 'Pending'), ('Return', 'Return'), ('Shipped', 'Shipped')], default='Pending', max_length=150),
        ),
    ]
