# Generated by Django 4.2 on 2023-06-08 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0045_remove_order_status_orderitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('Cancelled', 'Cancelled'), ('Delivered', 'Delivered'), ('Pending', 'Pending'), ('Return', 'Return'), ('Shipped', 'Shipped'), ('Processing', 'Processing')], default='Pending', max_length=150),
        ),
    ]
