# Generated by Django 4.2 on 2023-06-14 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0049_alter_orderitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('Shipped', 'Shipped'), ('Cancelled', 'Cancelled'), ('Delivered', 'Delivered'), ('Return', 'Return'), ('Processing', 'Processing'), ('Pending', 'Pending')], default='Pending', max_length=150),
        ),
    ]
