# Generated by Django 4.2 on 2023-06-05 19:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userprofile', '0003_walet'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Walet',
            new_name='Wallet',
        ),
    ]
