# Generated by Django 4.2 on 2023-06-08 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_rename_wallet_wallet_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='wallet',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
