# Generated by Django 4.2 on 2023-06-14 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='geeksmodel',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='geeksmodel',
            name='photo',
            field=models.ImageField(default=1, upload_to='photos/variations'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='geeksmodel',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
